config/routes.rb
Rails.application.routes.draw do
  resources :open_practices
  devise_for :admins, skip: :registrations

  get '/about', to: 'static_pages#about', as: 'about'

  get '/events', to: 'derby_events#index', as: 'event_index'
  get '/events/submit', to: 'derby_events#new', as: 'event_submit'
  post '/events/submit', to: 'derby_events#create'
  patch '/events/submit', to: 'derby_events#update'

  get '/events/thanks', to: 'derby_events#thanks', as: 'event_thanks'

  get '/practices', to: 'open_practices#index', as: 'practice_index'
  get '/practices/submit', to: 'open_practices#new', as: 'practice_submit'
  post '/practices/submit', to: 'open_practices#create'
  patch '/practices/submit', to: 'open_practices#update'

  get '/practices/thanks', to: 'open_practices#thanks', as: 'practice_thanks'

  devise_scope :admin do
    get '/sign_in', to: 'devise/sessions#new', as: 'sign_in'
  end

  resources :derby_events
  resources :open_practices

  root 'static_pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Adjusted devise modules for admin only. Others available are:
  # :confirmable, :omniauthable, :registerable, :recoverable, :validatable
  devise :database_authenticatable, :trackable, :timeoutable, :lockable, :rememberable
end

app/models/derby_event.rb
class DerbyEvent < ActiveRecord::Base
  GENDERS = %w(Male Female Co-Ed)
  RULESETS = %w(mrda wftda jrda made usars rdcl)

  scope :viewable, -> { where(approved: true, deleted: false) }
  scope :upcoming, -> { where("start_date >= ? OR end_date >= ?", Date.today, Date.today) }

  def viewable?
    approved && !deleted
  end

  def rulesets
    RULESETS.select {|ruleset| send(ruleset)}
  end

  def genders
    GENDERS.select do |gender|
      send(gender.downcase.gsub(/[^a-z]/, ''))
    end
  end
end

app/models/open_practice.rb
class OpenPractice < ActiveRecord::Base
  DAYS = %w(monday tuesday wednesday thursday friday saturday sunday)

  scope :viewable, -> { where(approved: true, deleted: false) }

  def viewable?
    approved && !deleted
  end

  def days
    DAYS.select {|day| send(day)}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/url_formatter.rb
module URLFormatter
  extend ActiveSupport::Concern

  private
  def format_url_for_db(url)
    unless url[0..6] == 'http://'
      "http://#{url}"
    else
      url
    end
  end
end

app/controllers/derby_events_controller.rb
class DerbyEventsController < ApplicationController
  include URLFormatter

  before_action :set_derby_event, only: [:show, :edit, :update]

  # GET /derby_events
  def index
    @title = "Derby Event List -"
    if admin_signed_in?
      @derby_events = DerbyEvent.upcoming
    else
      @derby_events = DerbyEvent.viewable.upcoming
    end
    @derby_events = @derby_events.map {|derby_event| DerbyEventPresenter.new(derby_event)}
  end

  # GET /derby_events/1
  def show
    @derby_event = DerbyEventPresenter.new(@derby_event)
    unless @derby_event.viewable? || admin_signed_in?
      redirect_to root_path
      return
    end
    respond_to do |format|
      format.html { render layout: false }
    end
  end

  # GET /derby_events/new
  def new
    @title = "Submit an Event -"
    @derby_event = DerbyEvent.new
  end

  # GET /derby_events/1/edit
  def edit
    redirect_to root_path unless admin_signed_in?
  end

  # POST /derby_events
  def create
    @derby_event = DerbyEvent.new(derby_event_params)

    respond_to do |format|
      if @derby_event.save
        format.html { redirect_to event_thanks_path }
      else
        format.html { render :new }
      end
    end
  end

  def thanks
  end

  # PATCH/PUT /derby_events/1
  def update
    redirect_to root_path unless admin_signed_in?
    respond_to do |format|
      if @derby_event.update(derby_event_params)
        format.html { redirect_to root_path, notice: 'Event was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /derby_events/1
  def destroy
    redirect_to root_path unless admin_signed_in?
    @derby_event.destroy
    respond_to do |format|
      format.html { redirect_to derby_events_url, notice: 'Derby event was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_derby_event
      @derby_event = DerbyEvent.find(params[:id])
    end

    def format_date_for_db(form_date)
      month, day, year = form_date.split('/')
      "#{year}-#{month}-#{day}"
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def derby_event_params
      event_params = params.require(:derby_event).permit(:name, :start_date, :start_time, :end_date, :end_time, :venue, :city, :state, :postal_code, :country, :host, :website, :event_contact, :cost, :mrda, :wftda, :jrda, :made, :usars, :rdcl, :female, :male, :coed, :preregistration, :spectators, :general_info, :submission_contact, :approved, :deleted)

      unless event_params[:website].blank?
        event_params[:website] = format_url_for_db(event_params[:website])
      end
                                              
      [:start_date, :end_date].each do |date_field|
        unless event_params[date_field].blank?
          event_params[date_field] = format_date_for_db(event_params[date_field])
        end
      end

      event_params
    end
end

app/controllers/open_practices_controller.rb
class OpenPracticesController < ApplicationController
  include URLFormatter

  before_action :set_open_practice, only: [:show, :edit, :update]

  # GET /open_practices
  def index
    @title = "Open Practice List -"
    if admin_signed_in?
      @open_practices = OpenPractice.all
    else
      @open_practices = OpenPractice.viewable
    end
    @open_practices = @open_practices.map {|open_practice| OpenPracticePresenter.new(open_practice)}
  end

  # GET /open_practices/1
  def show
    @open_practice = OpenPracticePresenter.new(@open_practice)
    unless admin_signed_in? || @open_practice.viewable?
      redirect_to root_path
      return
    end
    respond_to do |format|
      format.html { render layout: false }
    end
  end

  # GET /open_practices/new
  def new
    @title = "Submit an Open Practice -"
    @open_practice = OpenPractice.new
  end

  # GET /open_practices/1/edit
  def edit
    redirect_to root_path unless admin_signed_in?
  end

  def thanks
  end

  # POST /open_practices
  def create
    @open_practice = OpenPractice.new(open_practice_params)

    respond_to do |format|
      if @open_practice.save
        format.html { redirect_to practice_thanks_path }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /open_practices/1
  def update
    redirect_to root_path unless admin_signed_in?
    respond_to do |format|
      if @open_practice.update(open_practice_params)
        format.html { redirect_to root_path, notice: 'Practice was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /open_practices/1
  def destroy
    redirect_to root_path unless admin_signed_in?
    @open_practice.destroy
    respond_to do |format|
      format.html { redirect_to open_practices_url, notice: 'Open practice was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_open_practice
      @open_practice = OpenPractice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def open_practice_params
      practice_params = params.require(:open_practice).permit(:league_name, :league_website, :city, :state, :postal_code, :country, :venue, :cost, :monday, :monday_start, :monday_end, :tuesday, :tuesday_start, :tuesday_end, :wednesday, :wednesday_start, :wednesday_end, :thursday, :thursday_start, :thursday_end, :friday, :friday_start, :friday_end, :saturday, :saturday_start, :saturday_end, :sunday, :sunday_start, :sunday_end, :venue, :practice_contact, :submission_contact, :approved, :deleted)

      unless practice_params[:league_website].blank?
        practice_params[:league_website] = format_url_for_db(practice_params[:league_website])
      end

      practice_params
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
    @title = "About -"
  end

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/open_practices_helper.rb
module OpenPracticesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/derby_events/_event_list.html.slim
.modal.fade#event-modal tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content#event-modal-content
      .modal-body
        .h3 Loading...

.panel.panel-default.col-md-10.col-md-offset-1.event-list
  - if @derby_events.empty?
    p.text-center
      |No events found. Have one to share? 
      a href=event_submit_path Submit it!
  - else
    .table-responsive#event-div
      input.search placeholder="Search"
      table.table.table-hover.table-condensed#event-table
        thead
          tr
            th Date
            th Event
            th City
            th State/Province
            th Country
        tbody.list
          - @derby_events.each do |event|
            tr data-toggle="modal" data-target="#event-modal" data-event-id=event.id class=(admin_signed_in? && event.approved ? 'success' : '')
              td.date = event.start_date.strftime('%m/%d/%Y').html_safe
              td.name = event.name.html_safe
              td.city = event.city.html_safe
              td.state = event.state.html_safe
              td.country = event.country_name.html_safe
              - if admin_signed_in?
                td = link_to "Edit", edit_derby_event_path(event.id)

app/views/derby_events/_form.html.slim
= bootstrap_form_for @derby_event do |f|
  - if @derby_event.errors.any?
    #error_explanation
      h2 = "#{pluralize(@derby_event.errors.count, "error")} prohibited this event from being saved:"
      ul
        - @derby_event.errors.full_messages.each do |message|
          li = message

  .row
    .col-md-8
      p 
        | Where to Roll is your one-stop search for open roller derby scrimmages and clinics around the world. 
        | Submitted events should be open for participation to roller derby skaters from any league. If you 
        | have any questions or concerns about your event's eligibility or if you've already submitted your event 
        | and details have changed, please contact us by 
        a href="mailto:info@wheretoroll.com" email
        |  or 
        a href="https://www.facebook.com/wheretoroll" Facebook
        | .
  .row
    br
  .row
    .col-md-6
      = f.email_field :submission_contact, label: "Your Email Address", hide_label: true, placeholder: "Your Email Address", help: "We promise only to use this to contact you regarding this submission.", icon: "asterisk"
  .row
    .col-md-6
      = f.text_field :name, label: "Event Name", hide_label: true, placeholder: "Event Name", icon: "asterisk"
  .row
    .col-md-3
      .form-group.has-feedback
        .input-group.date#start_date_group
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
          input.form-control#start_date type="text" name="derby_event[start_date]" placeholder="Start Date" value="#{@derby_event.start_date.present? ? @derby_event.start_date.strftime("%m/%d/%Y") : ""}"
          span.glyphicon.glyphicon-asterisk.form-control-feedback
    .col-md-3
      .form-group
        .input-group.date#start_time_group
          span.input-group-addon
            span.glyphicon.glyphicon-time
          input.form-control#start_time type="text" data-date-format="h:mm A" name="derby_event[start_time]" placeholder="Start Time" value="#{@derby_event.start_time.present? ? @derby_event.start_time.strftime("%l:%M %p") : ""}"
  .row
    .col-md-3
      .form-group
        .input-group.date#end_date_group
          span.input-group-addon
            span.glyphicon.glyphicon-calendar
          input.form-control#end_date type="text" name="derby_event[end_date]" placeholder="End Date" value="#{@derby_event.end_date.present? ? @derby_event.end_date.strftime("%m/%d/%Y") : ""}"
    .col-md-3
      .form-group
        .input-group.date#end_time_group
          span.input-group-addon
            span.glyphicon.glyphicon-time
          input.form-control#end_time type="text" data-date-format="h:mm A" name="derby_event[end_time]" placeholder="End Time" value="#{@derby_event.end_time.present? ? @derby_event.end_time.strftime("%l:%M %p") : ""}"
  .row
    .col-md-6
      = f.text_field :venue, hide_label: true, placeholder: "Venue Name and/or Street Address"
  .row
    .col-md-3
      = f.text_field :city, hide_label: true, placeholder: "City", icon: "asterisk"
  .row
    .col-md-3
      = f.text_field :state, hide_label: true, placeholder: "State/Province"
  .row
    .col-md-2
      = f.text_field :postal_code, hide_label: true, placeholder: "Postal Code"
  .row
    .col-md-2
      .form-group
        = f.label :country, "Country", { class: 'control-label' }
        span.glyphicon.glyphicon-asterisk
        = f.country_select :country, { priority_countries: ["AU", "AR", "BS", "BE", "BR", "CA", "CL", "CO", "DK", "FI", "FR", "DE", "GR", "IE", "IT", "JP", "MX", "NL", "NZ", "NO", "PT", "PR", "ZA", "ES", "SE", "CH", "GB", "UM", "US", "VG", "VI"] }, class: 'form-control'
  .row
    br
  .row
    .col-md-4
      = f.text_field :host, hide_label: true, placeholder: "Host League, Coach, or Organization"
  .row
    .col-md-3
      = f.text_field :website, hide_label: true, placeholder: "Link to Online Event Details"
  .row
    .col-md-3
      = f.email_field :event_contact, hide_label: true, placeholder: "Event Contact Email"
  .row
    .col-md-2
      = f.text_field :cost, hide_label: true, placeholder: "Cost"
  .row
    .col-md-12
      h4 Rulesets
      p Please select all rulesets that will be played at this event.
      = f.form_group :ruleset
        = f.check_box :mrda, label: "MRDA", inline: true
        = f.check_box :wftda, label: "WFTDA", inline: true
        = f.check_box :jrda, label: "JRDA", inline: true
        = f.check_box :made, label: "MADE", inline: true
        = f.check_box :usars, label: "USARS", inline:true
        = f.check_box :rdcl, label: "RDCL", inline:true
  .row
    .col-md-12
      h4 Genders
      p Please select all that apply to this event.
      = f.form_group :gender
        = f.check_box :female, label: "Female", inline: true
        = f.check_box :male, label: "Male", inline: true
        = f.check_box :coed, label: "Co-Ed", inline: true
  .row
    .col-md-12
      = f.check_box :preregistration, label: "Preregistration available?"
  .row
    .col-md-12
      = f.check_box :spectators, label: "Spectators allowed?"
  - if admin_signed_in?
    .row
      .col-md-12
        = f.check_box :approved, label: "Approved?", help: "Approved events will appear for all users on the main site."
  .row
    .col-md-6
      h4 Event Details
      p Please include any details not already covered in this submission form. This could include links to sign-up forms, specifics/theme of your event, hotel/parking information, suggested skater skill levels, etc.
      = f.text_area :general_info, hide_label: true, rows: 5
  .row
    br
  .row
    .col-md-1
      a.btn.btn-default role="button" href="#{root_path}" Cancel
    .col-md-1
      .actions = f.submit "Submit"
  .row
    br

app/views/derby_events/edit.html.slim
.index-container
  .col-md-offset-2
    h1 Edit Event

    == render 'form'

app/views/derby_events/index.html.slim
.container-fluid.index-container
  .row
    br
  .row
    .col-md-8.col-md-offset-1
      h1 Derby Events
      p
        | These upcoming events are open to skaters from multiple leagues. Click an event for more details and 
        | specifics on how to sign up. If you find a 
        | mistake in a listing or get details from an organizer that differ from what you see here, 
        | please let us know by 
        a href="mailto:info@wheretoroll.com" email
        |  or 
        a href="https://www.facebook.com/wheretoroll" Facebook
        |  so we can keep everything up to date and accurate.
  .row
    br
  .row
    == render "event_list"

app/views/derby_events/new.html.slim
.index-container
  .col-md-offset-2
    h1 Submit an Event

    == render 'form'

app/views/derby_events/show.html.slim
.modal-header
  button.close type="button" data-dismiss="modal" aria-label="Close"
    span aria-hidden="true" &times;
  h3.modal-title
    - if !@derby_event.website.empty?
      a href=@derby_event.website target="_blank" =@derby_event.name
    - else
      =@derby_event.name
    - if !@derby_event.host.empty?
      br
      span.small
        |Hosted by 
        =@derby_event.host
.modal-body
  .container-fluid
    .row
      .col-md-3
        strong When
      .col-md-9
        =@derby_event.display_datetime
    .row
      br
    .row
      .col-md-3
        strong Where
      .col-md-9
        == @derby_event.location_html
    .row
      br
    .row
      .col-md-3
        strong Rulesets
      .col-md-9
        = @derby_event.rulesets.empty? ? 'none specified' : @derby_event.rulesets
    .row
      .col-md-3
        strong Genders
      .col-md-9
        = @derby_event.genders.empty? ? 'none specified' : @derby_event.genders
    .row
      br
    .row
      .col-md-3
        strong Cost
      .col-md-9
        = @derby_event.cost.empty? ? 'not specified' : @derby_event.cost
    .row
      br
    .row
      .col-md-3
        strong Preregistration?
      .col-md-9
        = @derby_event.preregistration ? 'Yes' : 'No'
    .row
      .col-md-3
        strong Spectators?
      .col-md-9
        = @derby_event.spectators ? 'Yes' : 'No'
    .row
      br
    .row
      .col-md-3
        strong Contact
      .col-md-9
        - if @derby_event.event_contact.empty?
          |not specified
        - else
          a href="mailto:#{@derby_event.event_contact}"
            = @derby_event.event_contact
    .row
      br
    .row
      .col-md-12
        - if !@derby_event.general_info.empty?
          span
            strong Other Information
          .panel.panel-default
            .panel-body
              = auto_link @derby_event.general_info.gsub(/\r?\n/, '<br>')
.modal-footer
  .row
    .col-md-2.text-left
      a href="https://www.facebook.com/sharer/sharer.php?u=#{root_url}?shared_event=#{@derby_event.id}" target="_blank"
        = image_tag "fbshare.png"
    .col-md-10.text-right
      |Shareable link: 
      a href="#{root_url}?shared_event=#{@derby_event.id}" target="_blank"
        = "#{root_url}?shared_event=#{@derby_event.id}"

app/views/derby_events/thanks.html.slim
.container-fluid
  .col-md-1
  .col-md-10
    h2 Thank you!
    p
    | Thanks very much for letting us know about your event. We'll review it as soon as possible, get in touch with you if we have any questions, and add your event to our list. In the meantime, feel free to contact us by 
    a href="mailto:info@wheretoroll.com" email
    |  or via 
    a href="https://www.facebook.com/wheretoroll" Facebook
    |  if you have any questions or changes to make.

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a? String
    .alert.alert class="alert-#{name.to_s == 'notice' ? 'success' : 'danger'}" role="alert"
      button.close type="button" data-dismiss="alert" aria-hidden="true" &times;
      div id="flash_#{name}" =msg

app/views/layouts/application.html.slim
doctype html
html
  head
    meta name="viewport" content="width=device-width, initial-scale=1"
    meta name="description" content="Where to Roll is your one-stop search for open roller derby scrimmages and clinics around the world."

    / this is for facebook
    meta property="og:url" content="http://www.wheretoroll.com/"
    meta property="og:description" content="Where to Roll is your one-stop search for open roller derby scrimmages and clinics around the world."
    meta property="og:title" content="Where to Roll"
    meta property="og:site_name" content="Where to Roll"
    meta property="og:image" content=image_url("og-logo.png")
    meta property="og:image:type" content="image/png"
    meta property="og:image:width" content="1200"
    meta property="og:image:height" content="630"

    meta charset="utf-8"

    title Where to Roll - #{@title} Open Roller Derby Clinics, Scrimmages, Mashups and Practices

    link href="https://fonts.googleapis.com/css?family=Didact+Gothic" rel="stylesheet" type="text/css"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    / this is for google analytics
    script
      |
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
          ga('create', 'UA-64649704-1', 'auto');
          ga('send', 'pageview');
  body
    .logo-circle
    nav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        .navbar-header
          button.navbar-toggle.collapsed type="button" data-toggle="collapse" data-target="#home-navbar" aria-expanded="false"
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href="#{root_path}" =image_tag('w2r-round-150x150.png', size: '100x100', alt: 'Where to Roll', class: 'brand-icon')

        #home-navbar.collapse.navbar-collapse
          ul.nav.navbar-nav
            li.dropdown class=('active' if current_page?(event_index_path) || current_page?(event_submit_path))
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                | Events 
                span.caret
              ul.dropdown-menu
                li
                  a href=event_index_path View
                li
                  a href=event_submit_path Submit
            li.dropdown class=('active' if current_page?(practice_index_path) || current_page?(practice_submit_path))
              a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
                | Practices 
                span.caret
              ul.dropdown-menu
                li
                  a href=practice_index_path View
                li
                  a href=practice_submit_path Submit
            li class=('active' if current_page? about_path)
              a href=about_path
                | About
                - if current_page? about_path
                  span.sr-only
                    | (current)
            -if admin_signed_in?
              li
                = link_to destroy_admin_session_path, method: :delete
                  | Sign Out

    = render 'layouts/messages'
    == yield

    footer.navbar.navbar-default.navbar-fixed-bottom
      .container-fluid
        .row
          .col-md-11.navbar-text
            span &copy; 2015 wheretoroll.com All Rights Reserved
            a href="https://www.facebook.com/wheretoroll"
              span.pull-right =image_tag('FB_FindUsOnFacebook-100.png', alt: 'Find us on Facebook')

app/views/open_practices/_practice_list.html.slim
.modal.fade#event-modal tabindex="-1" role="dialog"
  .modal-dialog role="document"
    .modal-content#event-modal-content
      .modal-body
        .h3 Loading...

.panel.panel-default.col-md-10.col-md-offset-1.event-list
  - if @open_practices.empty?
    p.text-center
    |No open practices found. Have one to share? 
    a href=practice_submit_path Submit it!
  - else
    .table-responsive#practice-div
      input.search placeholder="Search"
      table.table.table-hover.table-condensed#event-table
        thead
          tr
            th League
            th City
            th State/Province
            th Country
        tbody.list
          - @open_practices.each do |practice|
            tr data-toggle="modal" data-target="#event-modal" data-practice-id=practice.id class=(admin_signed_in? && practice.approved ? 'success' : '')
              td.league = practice.league_name.html_safe
              td.city = practice.city.html_safe
              td.state = practice.state.html_safe
              td.country = practice.country_name.html_safe
              - if admin_signed_in?
                td = link_to "Edit", edit_open_practice_path(practice.id)

app/views/open_practices/edit.html.slim
.index-container
  .col-md-offset-2
    h1 Edit Practice

    == render 'form'

app/views/open_practices/index.html.slim
.container-fluid.index-container
  .row
    br
  .row
    .col-md-8.col-md-offset-1
      h1 Open Practices
      p
        | These are practices that leagues have indicated are open to outside skaters. Because practice times 
        | and locations can often change on short notice for many leagues, make sure you get in touch with the 
        | listed contact before attending a practice. That will also give you a chance to confirm the ruleset, 
        | gender and other league specific details. If you find out that a league's schedule has permanently 
        | changed, please let let us know by 
        a href="mailto:info@wheretoroll.com" email
        |  or 
        a href="https://www.facebook.com/wheretoroll" Facebook
        |  so we can keep everything up to date and accurate.
  .row
    br
  .row
    == render "practice_list"

app/views/open_practices/new.html.slim
.index-container
  .col-md-offset-2
    h1 Submit an Open Practice

    == render 'form'

app/views/open_practices/show.html.slim
.modal-header
  button.close type="button" data-dismiss="modal" aria-label="Close"
    span aria-hidden="true" &times;
  h3.modal-title
    - if !@open_practice.league_website.empty?
      a href=@open_practice.league_website target="_blank" =@open_practice.league_name
    - else
      =@open_practice.league_name
.modal-body
  .container-fluid
    .row
      .col-md-3
        strong When
      .col-md-9
        == @open_practice.display_days
    .row
      br
    .row
      .col-md-3
        strong Where
      .col-md-9
        == @open_practice.location_html
    .row
      br
    .row
      .col-md-3
        strong Cost
      .col-md-9
        = @open_practice.cost.empty? ? 'not specified' : @open_practice.cost
    .row
      br
    .row
      .col-md-3
        strong Contact
      .col-md-9
        - if @open_practice.practice_contact.empty?
          |not specified
        - else
          a href="mailto:#{@open_practice.practice_contact}"
            = @open_practice.practice_contact
    .row
      br

app/views/open_practices/thanks.html.slim
.container-fluid
  .col-md-1
  .col-md-10
    h2 Thank you!
    p
    | Thanks very much for letting us know about your practice. We'll review it as soon as possible, get in touch with you if we have any questions, and add your practice to our list. In the meantime, feel free to contact us by 
    a href="mailto:info@wheretoroll.com" email
    |  or via 
    a href="https://www.facebook.com/wheretoroll" Facebook
    |  if you have any questions or changes to make.

app/views/static_pages/about.html.slim
.row
  br
.row
  .col-md-8.col-md-offset-2
    p Where to Roll is your one-stop search for open roller derby scrimmages, clinics and practices around the world!
    p
      | The goal of the Where To Roll team is to provide an easy to use, up-to-date database to make your already 
      | hectic derby life easier. This searchable database will include scrimmage, clinic and practice opportunities from all 
      | over the world for all skill levels, ages, and genders.
    p 
      | Check back here and follow us on 
      a href="http://www.facebook.com/wheretoroll" Facebook
      |  to be the first to know Where to Roll!
    br
    p
      | Background photo courtesy of 
      a href="https://www.facebook.com/Bryan.McLeod" ThunderBuddy Studios

app/views/static_pages/index.html.slim
.logo-container
.container-fluid.index-container
  .row
    br
    br
  .row
    .col-md-3.col-md-offset-3
      a.btn.btn-default.btn-xl.btn-block role="button" href=event_index_path View Events
    .col-md-3
      a.btn.btn-default.btn-xl.btn-block role="button" href=practice_index_path View Open Practices
  .row
    br
  .row
    .col-md-3.col-md-offset-3
      a.btn.btn-default.btn-xl.btn-block role="button" href=event_submit_path Submit an Event
    .col-md-3
      a.btn.btn-default.btn-xl.btn-block role="button" href=practice_submit_path Submit an Open Practice